<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VisualWeb.Renderer</RootNamespace>
    <AssemblyName>VisualWeb.Renderer</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../VisualWeb.PageRendering/VisualWeb.PageRendering.csproj" />
    <ProjectReference Include="../../Ipc/Ipc.Transport/Ipc.Transport.csproj" />
    <ProjectReference Include="../../Platform/Platform.Linux.Sandbox/Platform.Linux.Sandbox.csproj" />
  </ItemGroup>
</Project>
