<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/Engine/Engine.Paint/Engine.Paint.csproj" />
    <ProjectReference Include="../../src/Engine/Engine.Html/Engine.Html.csproj" />
    <None Include="../Engine.Text.Tests/Data/NotoSans.ttf" Link="Data/NotoSans.ttf" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Data/*.rgba" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
