<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <RootNamespace>VisualWeb.Browser.Tests</RootNamespace>
    <AssemblyName>VisualWeb.Browser.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../../src/Apps/VisualWeb.Browser/VisualWeb.Browser.csproj" />
    <None Include="../Engine.Text.Tests/Data/NotoSans.ttf" Link="Data/NotoSans.ttf" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
