<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>VisualWeb.PageRendering</RootNamespace>
    <AssemblyName>VisualWeb.PageRendering</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Engine/Engine.Content/Engine.Content.csproj" />
    <ProjectReference Include="../../Engine/Engine.Scripting/Engine.Scripting.csproj" />
    <ProjectReference Include="../../Core/Core.Url/Core.Url.csproj" />
  </ItemGroup>
</Project>
