<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Platform/Platform.Linux/Platform.Linux.csproj" />
    <ProjectReference Include="../../src/Platform/Platform.Windows/Platform.Windows.csproj" />
  </ItemGroup>
</Project>
