<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VisualWeb.V8Smoke</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Engine/Engine.Scripting/Engine.Scripting.csproj" />
    <ProjectReference Include="../../src/Platform/Platform.Linux.Sandbox/Platform.Linux.Sandbox.csproj" />
    <ProjectReference Include="../../src/Platform/Platform.Windows.Sandbox/Platform.Windows.Sandbox.csproj" />
  </ItemGroup>
</Project>
